services:
  - type: web
    name: app-taxi
    runtime: node
    buildCommand: (cd client && npm install && npm run build) && (cd server && npm install)
    startCommand: node server/src/seed/init-database.js; node server/src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ENCRYPTION_KEY
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:5173
